# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ AUTOSTART
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

exec-once = gentoo-pipewire-launcher restart & 
exec-once = awww-daemon
exec-once = swayosd-server --top-margin 0.9 --style "$HOME/.config/swayosd/style.css"
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/volume_listener.sh
exec-once = qs -p ~/.config/quickshell/shell.qml &
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1 &
exec-once = swaybg -i /home/nana/Pictures/wallpaper/dopesmoker_gruvbox.png &
exec-once = hypridle -w timeout 300 'hyprlock' before-sleep 'hyprlock'
exec-once = ~/.config/hypr/scripts/update_notifier.sh
exec-once = hypridle
