# These settings were set by the catalyst build script that automatically
   2 │ # built this stage.
   3 │ # Please consult /usr/share/portage/config/make.conf.example for a more
   4 │ # detailed example.
   5 │ COMMON_FLAGS="-march=native -O2 -pipe"
   6 │ CFLAGS="${COMMON_FLAGS}"
   7 │ CXXFLAGS="${COMMON_FLAGS}"
   8 │ FCFLAGS="${COMMON_FLAGS}"
   9 │ FFLAGS="${COMMON_FLAGS}"
  10 │ RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
  11 │ MAKEOPTS="-j16 -l16"
  12 │ # Appending getbinpkg to the list of values within the FEATURES variable
  13 │ FEATURES="${FEATURES} getbinpkg"
  14 │ # Require signatures
  15 │ FEATURES="${FEATURES} binpkg-request-signature"
  16 │ PORTAGE_SCHEDULING_POLICY="idle"
  17 │ # NOTE: This stage was built with the bindist USE flag enabled
  18 │ FEATURES="ipc-sandbox candy parallel-fetch parallel-install sign network-sandbox"
  19 │ # This sets the language of build output to English.
  20 │ # Please keep this setting intact when reporting bugs.
  21 │ LC_MESSAGES=C.UTF-8
  22 │ VIDEO_CARDS="amdgpu radeonsi nvidia"
  23 │ INPUT_DEVICES="libinput synaptics"
  24 │ USE="dist-kernel X spice xorg spice usbredir gtk dbus ABI_X86=(64 32) png udisks udev alsa elogind policykit colord jpeg pavucontrol wifi wayland gles2 opengl networkmanager pulseaudio"
  25 │ ACCEPT_KEYWORDS="~amd64"
  26 │ ACCEPT_LICENSE="*"