─────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     │ File: /etc/portage/make.conf
─────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ # These settings were set by the catalyst build script that automatically
   2 │ # built this stage.
   3 │ # Please consult /usr/share/portage/config/make.conf.example for a more
   4 │ # detailed example.
   5 │ COMMON_FLAGS="-march=native -O2 -pipe"
   6 │ CFLAGS="${COMMON_FLAGS}"
   7 │ CXXFLAGS="${COMMON_FLAGS}"
   8 │ FCFLAGS="${COMMON_FLAGS}"
   9 │ FFLAGS="${COMMON_FLAGS}"
  10 │ 
  11 │ # NOTE: This stage was built with the bindist USE flag enabled
  12 │ 
  13 │ # This sets the language of build output to English.
  14 │ # Please keep this setting intact when reporting bugs.
  15 │ LC_MESSAGES=C.UTF-8
  16 │ MAKEOPTS="-j16 -l16"
  17 │ PORTAGE_SCHEDULING_POLICY="idle"
  18 │ FEATURES="ipc-sandbox candy parallel-fetch parallel-install sign network-sandbox"
  19 │ VIDEO_CARDS="amdgpu radeonsi nvidia"
  20 │ INPUT_DEVICES="libinput synaptics"
  21 │ USE="dist-kernel X spice xorg spice usbredir gtk dbus ABI_X86=(64 32) png udisks udev alsa elogind policykit colord jpeg pavucontrol wifi wayland gles2 opengl 
     │ networkmanager pulseaudio"
  22 │ ACCEPT_KEYWORDS="~amd64"
  23 │ ACCEPT_LICENSE="*"
  24 │ # Appending getbinpkg to the list of values within the FEATURES variable
  25 │ FEATURES="${FEATURES} getbinpkg"
  26 │ # Require signatures
  27 │ FEATURES="${FEATURES} binpkg-request-signature"
  28 │ 
  29 │ GENTOO_MIRRORS="http://distfiles.gentoo.org"   
─────┴──────────────────────────────────────────────────