COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# Parallel builds (8 cores / 16 threads)
MAKEOPTS="-j16 -l16"
EMERGE_DEFAULT_OPTS="--jobs=8 --load-average=8"
PORTAGE_SCHEDULING_POLICY="idle"

# Consolidated Features (Hardened, Sandboxing, Binary Packages, and Candy)
FEATURES="splitdebug strict-compiler strict-paths protect-owned binpkg-requester assume-digests ipc-sandbox candy parallel-fetch parallel-install sign network-sandbox getbinpkg binpkg-request-signature"

PORTAGE_ELOG_CLASSES="warn error log"
PORTAGE_ELOG_SYSTEM="save_summary:log"

VIDEO_CARDS="amdgpu radeonsi nvidia"
INPUT_DEVICES="libinput synaptics"
USE="dist-kernel X spice xorg spice usbredir gtk dbus png udisks udev alsa elogind policykit colord jpeg pavucontrol wifi wayland gles2 opengl networkmanager pulseaudio"

# Language support
LINGUAS="en"
LC_MESSAGES="C"

# Networking and mirrors
GENTOO_MIRRORS="https://distfiles.gentoo.org"
SYNC="rsync://rsync.gentoo.org/gentoo-portage"

# License and keywords (Set globally to stable amd64)
ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="amd64"
