#!/usr/bin/bash

hypr=~/.config/hypr
scripts=$hypr/scripts

cooldown=0.1


while true
do
    case "$1" in
        "arrow-icon")
            if $scripts/toolbar_state; then
                echo ""
            else
                echo ""
            fi
            ;;
        # "media")
            
        *)
            if $scripts/toolbar_state; then
                echo "     "
            else
                echo ""
            fi
            ;;
    esac
    sleep $cooldown
done