background = {{colors.background.default.hex}}
foreground = {{colors.on_surface.default.hex}}
cursor-color = {{colors.primary.default.hex}}
selection-background = {{colors.primary_container.default.hex}}
selection-foreground = {{colors.on_surface.default.hex}}

palette = 0={{hype16.color0.default.hex}}
palette = 1={{hype16.color1.default.hex}}
palette = 2={{hype16.color2.default.hex}}
palette = 3={{hype16.color3.default.hex}}
palette = 4={{hype16.color4.default.hex}}
palette = 5={{hype16.color5.default.hex}}
palette = 6={{hype16.color6.default.hex}}
palette = 7={{hype16.color7.default.hex}}
palette = 8={{hype16.color8.default.hex}}
palette = 9={{hype16.color9.default.hex}}
palette = 10={{hype16.color10.default.hex}}
palette = 11={{hype16.color11.default.hex}}
palette = 12={{hype16.color12.default.hex}}
palette = 13={{hype16.color13.default.hex}}
palette = 14={{hype16.color14.default.hex}}
palette = 15={{hype16.color15.default.hex}}
