#!/bin/sh

case "$(file -Lb --mime-type -- "$1")" in
    image/*)
        chafa -f sixel -s "$2x$3" --animate off --polite on -t 0.9 --bg "#f0d8b3" "$1"
        exit 1
        ;;
    text/*)
        cat "$1"
        exit 0
        ;;
esac
