## Autogenerated config.py
##
## NOTE: config.py is intended for advanced users who are comfortable
## with manually migrating the config file on qutebrowser upgrades. If
## you prefer, you can also configure qutebrowser using the
## :set/:bind/:config-* commands without having to write a config.py
## file.
##
## Documentation:
##   qute://help/configuring.html
##   qute://help/settings.html

config.load_autoconfig(True)

# Quick Aliases
c.aliases = {
    'w': 'session-save', 'q': 'close', 'qa': 'quit', 'wq': 'quit --save', 'wqa': 'quit --save',
}


c.scrolling.bar = 'never'
c.content.user_stylesheets = [
    '~/.config/qutebrowser/css-themes/youtube-theme/sweet.css',
    '~/.config/qutebrowser/css-themes/global/global.css',
]


c.completion.open_categories = [
    'searchengines', 'quickmarks', 'bookmarks', 'history', 'filesystem'
]

c.confirm_quit = ['multiple-tabs']
c.auto_save.session = True
c.content.blocking.method = 'auto'

c.content.proxy = 'system'

# TOR - Enable or Disable
c.aliases = {
    'TOR': 'set content.proxy socks://localhost:9050', 'TOR-OFF': 'set content.proxy  system',
}

config.bind('<T>', 'TOR')
config.bind('<Escape>, <T>', 'TOR-OFF')

# System Settings

c.qt.force_platform = 'wayland'
c.qt.force_software_rendering = 'chromium'
c.spellcheck.languages = ['en-US']
c.tabs.show = 'multiple'
c.url.default_page = '~/.config/qutebrowser/startpage/index.html'

c.url.searchengines = {
    'DEFAULT': 'https://northboot.xyz/search?q={}',
    'od': 'https://www.odysee.com/$/search?q={} ',
    'cb': 'https://codeberg.org/explore/repos?sort=recentupdate&language=&topic=false&q={}',
    'gl': 'https://gitlab.com/explore/projects?sort=name_asc&name={}&sort=name_asc',
    'gh': 'https://github.com/search?q={}&type=repositories',
    'wk': 'https://en.wikipedia.org/w/index.php?search={}',
    'gw': 'https://wiki.gentoo.org/index.php?title=Special%3ASearch&search={}',
    'yt': 'https://youtube.com/results?search_query={}',
    'yi': 'https://yandex.com/images/search?text={}'
}

c.url.start_pages = '~/.config/qutebrowser/startpage/index.html'

config.source('themes/qute-city-lights/city-lights-theme.py')
