# heavily modified from https://codeberg.org/JustineSmithies/river-dotfiles 
# modified by wickedlester

nerdfont: &nerdfont Symbols Nerd Font Mono:pixelsize=14
jbmono: &jbmono JetBrainsMono Nerd Font:pixelsize=14
focused: &focused
  stack:
    - { background: { color: 313244cc } }
    - { overline: { size: 2, color: cba6f7ff } }
col-inv: &col-inv { foreground: 6c7086ff }

river_base: &river_base
  margin: 10
  text: "{id}"
  on-click: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"

bar:
  font: *jbmono
  height: 26
  location: top
  left-margin: 10
  right-spacing: 8
  right-margin: 10
  background: 1e1e2eff
  foreground: cdd6f4ff

  border:
    left-width: 0
    right-width: 0
    top-width: 0
    bottom-width: 2
    color: 6c7086ff

  left:
    - label:
        content:
          - string:
              on-click: "nwg-menu -va top -s menu-start-river.css -cmd-lock lockit -cmd-logout riverctl spawn pkill -TERM -u $USER -cmd-restart loginctl reboot -cmd-shutdown loginctl -i poweroff -term foot"
              text: 
              font: *nerdfont
              foreground: cba6f7ff
    - river:
        anchors:
          - *river_base
        title:
          - string:
              margin: 6
              text: "{layout}"
              foreground: fab387ff
              deco:
                background:
                  color: 45475acc
              on-click:
                left: sh -c "riverctl focus-view next"
                right: sh -c "riverctl focus-view previous"
                middle: sh -c "riverctl send-layout-cmd rivercarro 'main-location-cycle left,monocle'"
                wheel-up: sh -c "riverctl spawn 'cycle-focused-tags +1 10'"
                wheel-down: sh -c "riverctl spawn 'cycle-focused-tags -1 10'"

          - string:
              margin: 6
              text: "{title}"
              max: 50
              foreground: a6adc8ff
        content:
          map:
            conditions:
              id >= 11: { string: { text: "" } }
              state == focused:
                string:
                  <<: *river_base
                  deco: *focused
                  foreground: cba6f7ff
              state == urgent:
                string:
                  <<: *river_base
                  foreground: f38ba8ff
              state == unfocused:
                string:
                  <<: *river_base
              state == invisible:
                map:
                  conditions:
                    occupied:
                      string:
                        <<: *river_base
                        deco:
                          stack:
                            - overline: { size: 3, color: 00000000 }
                    ~occupied:
                      map:
                        deco: { background: { color: 00000000 } }
                        default:
                          empty: {}
                        conditions:
                          id == 1: { string: { <<: [*river_base, *col-inv] } }
                          id == 2: { string: { <<: [*river_base, *col-inv] } }
                          id == 3: { string: { <<: [*river_base, *col-inv] } }
                          id == 4: { string: { <<: [*river_base, *col-inv] } }
                          id == 5: { string: { <<: [*river_base, *col-inv] } }
                          id == 6: { string: { <<: [*river_base, *col-inv] } }
                          id == 7: { string: { <<: [*river_base, *col-inv] } }
                          id == 8: { string: { <<: [*river_base, *col-inv] } }
                          id == 9: { string: { <<: [*river_base, *col-inv] } }
                          id == 10: { string: { <<: [*river_base, *col-inv] } }
  center:
    - script:
        path: ~/.config/yambar/scripts/dater.sh
        args: []
        content:
          string:
            margin: 0
            text: "{date}"
            foreground: fab387ff
            on-click:
              left: sh -c "~/.config/yambar/scripts/calendar.sh show"
              right: sh -c "foot -T calcurse calcurse"
    - clock:
        time-format: "%I:%M %P"
        content:
          - string:
              margin: 0
              text: "{time}"
              foreground: fab387ff

  right:
    - mpd:
        host: "/tmp/mpd_socket"
        port: 6600
        content:
          string:
            text: "{artist} -{title} [{state}]"
            foreground: cba6f7ff
            on-click:
              left: mpc prev
              middle: mpc toggle
              right: mpc next
    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
                - string:
                    text: 
                    font: *nerdfont
                    foreground: 94e2d5ff
                - string:
                    text: " {cpu}%"
                    foreground: 94e2d5ff
    - mem:
        poll-interval: 2500
        content:
          - string:
              text: 
              font: *nerdfont
              foreground: a6e3a1ff
          - string:
              text: " {used:mb}MB/{total:mb}MB"
              foreground: a6e3a1ff
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted:
                string:
                  text: "0%"
                  foreground: 74c7ecff
                  on-click:
                    middle: sh -c "pactl set-sink-mute @DEFAULT_SINK@ toggle"
              ~muted:
                string:
                  text: "{cubic_volume}%"
                  foreground: 74c7ecff
                  on-click:
                    left: sh -c "pactl set-sink-volume @DEFAULT_SINK@ -2%"
                    middle: sh -c "pactl set-sink-mute @DEFAULT_SINK@ toggle"
                    right: sh -c "pactl set-sink-volume @DEFAULT_SINK@ +2%"
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string:
                              {
                                text: "󰋋",
                                font: *nerdfont,
                                foreground: "b4befeff",
                              }
                          muted:
                            string:
                              text: "󰝟"
                              font: *nerdfont
                              foreground: "6c7086ff"
                          ~muted:
                            - ramp:
                                tag: cubic_volume
                                items:
                                  - string:
                                      text: "󰕿"
                                      font: *nerdfont
                                      foreground: "89dcebff"
                                  - string:
                                      text: "󰖀"
                                      font: *nerdfont
                                      foreground: "74c7ecff"
                                  - string:
                                      text: "󰕾"
                                      font: *nerdfont
                                      foreground: "89b4faff"
                    type == "source":
                      string:
                        text: ""
                        font: *nerdfont
                        left-margin: 5
                        foreground: "b4befeff"
              - map:
                  <<: *volume
    - script:
        path: /home/ron/.config/yambar/scripts/discord_yambar.sh
        args: []
        content:
          string:
            text: ""
            foreground: f9f9f9ff
            on-click: sh -c "/home/ron/.config/yambar/scripts/discord.sh"
        poll-interval: 250
    - network:
        content:
          map:
            conditions:
              "name == enp7s0":
                map:
                  default:
                    - string:
                        { text: "󰲜", font: *nerdfont, foreground: "ffffffff" }
                  conditions:
                    "state == up":
                      - string:
                          text: "󰈀"
                          font: *nerdfont
                          foreground: "ffffffff"
                          on-click:
                            left: sh -c "networkmanager_dmenu"
                    "state == down":
                      - string:
                          text: "󰲜"
                          font: *nerdfont
                          foreground: "ffffffff"
    - label:
        content:
          - string:
              on-click: blueman-manager
              text: 󰂯
              font: *nerdfont
              foreground: ffffffff
    - script:
        path: ~/.config/yambar/scripts/idleinhibit.sh
        args: []
        content:
          string:
            margin: 0
            text: "{idleinhibit}"
            foreground: f9e2afff
            font: *nerdfont
            on-click: sh -c "~/.config/yambar/scripts/idleinhibit.sh toggle"
    - script:
        path: ~/.config/yambar/scripts/toggle-wlsunset.sh
        args: []
        content:
          string:
            margin: 0
            text: "{wlsunset}"
            foreground: f9e2afff
            font: *nerdfont
            on-click: sh -c "/home/ron/.config/yambar/scripts/toggle-wlsunset.sh toggle"
    - label:
        content:
          - string:
              on-click: wlogout -l /home/ron/.config/river/wlogout/layout -c /home/ron/.config/river/wlogout/style.css -b 2 -T 200 -B 200
              text: ⏻
              font: *nerdfont
              foreground: f38ba8FF
