require("custom.plugins")

require("custom.configs.pyright")
require("custom.configs.lua_ls")
require("custom.configs.bashls")
require("custom.configs.jsonls")
require("custom.configs.yamlls")
require("custom.configs.dockerls")
require("custom.configs.jsonnet_ls")
require("custom.configs.ada_ls")
require("custom.configs.ansiblels")
require("custom.configs.clangd")
require("custom.configs.cmake")
require("custom.configs.cssls")
require("custom.configs.gitlab_ci_ls")
require("custom.configs.golangci_lint_ls")
--require("custom.configs.grammarly")
require("custom.configs.jinja_lsp")
