hl.on("hyprland.start", function()
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/cliphist-watch.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("/usr/libexec/polkit-gnome-authentication-agent-1 &")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("gammastep -l 41.525032:-88.081726 &")
    hl.exec_cmd("~/.config/hypr/xdg-portal-hyprland")
	hl.exec_cmd("gentoo-pipewire-launcher restart &")
	hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/wallpaper.sh init")
	hl.exec_cmd("swaybg -i /home/nana/Pictures/wallpaper/dopesmoker_gruvbox.png &")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/pill-daemon.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/lock-daemon.sh")
end)
