# fcitx5 input method. Comment out the source line in hyprland.conf if
# you don't use an IME, or replace with ibus / kime / etc. as needed.
exec-once = fcitx5 -d --replace

env = GTK_IM_MODULE,fcitx
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = SDL_IM_MODULE,fcitx
