[general]
bars = 128
sensitivity = 100
lower_cutoff_freq = 0
higher_cutoff_freq = 24000
autosens = 1

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
channels = mono
reverse = 1
mono_option = average
bar_delimiter = 59
frame_delimiter = 10
